Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 28: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 19: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 277, in main
    model = parser(sys.argv[1], preprocess=True)
  File "/home/pventura/PostaOpenDefAlg/parser/parser.py", line 193, in parser
    linenumber, "Missing tuples for relation %s" % current_rel.sym)
parser.parser.ParserError: Line 25: Missing tuples for relation T0
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 298, in main
    f = is_open_def(model, targets_rels)
  File "main.py", line 269, in is_open_def
    return is_open_def_recursive(start_block)
  File "main.py", line 250, in is_open_def_recursive
    recursive_call = is_open_def_recursive(b)
  File "main.py", line 250, in is_open_def_recursive
    recursive_call = is_open_def_recursive(b)
  File "main.py", line 250, in is_open_def_recursive
    recursive_call = is_open_def_recursive(b)
  [Previous line repeated 2 more times]
  File "main.py", line 247, in is_open_def_recursive
    blocks = block.step()
  File "main.py", line 212, in step
    f = self.formula & generators[i].formula_diferenciadora(index)  # formula valida
  File "main.py", line 121, in formula_diferenciadora
    return formulas.eq(self.last_term, self.sintactico[index])
IndexError: list index out of range
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 298, in main
    f = is_open_def(model, targets_rels)
  File "main.py", line 269, in is_open_def
    return is_open_def_recursive(start_block)
  File "main.py", line 250, in is_open_def_recursive
    recursive_call = is_open_def_recursive(b)
  File "main.py", line 250, in is_open_def_recursive
    recursive_call = is_open_def_recursive(b)
  File "main.py", line 250, in is_open_def_recursive
    recursive_call = is_open_def_recursive(b)
  [Previous line repeated 11 more times]
  File "main.py", line 247, in is_open_def_recursive
    blocks = block.step()
  File "main.py", line 212, in step
    f = self.formula & generators[i].formula_diferenciadora(index)  # formula valida
  File "main.py", line 121, in formula_diferenciadora
    return formulas.eq(self.last_term, self.sintactico[index])
IndexError: list index out of range
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 315, in main
    0].superrel.arity), "MODEL CHECKING FAILED!"
AssertionError: MODEL CHECKING FAILED!
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................